version: "3"
services:
  shitcoin-factory:
    build: ./
    image: shitcoin-factory
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    ports:
      - 8545:8545

  frontend:
    build: ./frontend/
    image: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 4200:4200
      - 9876:9876
    command: ng serve --host 0.0.0.0 --port 4200 --poll=1000

volumes:
  exclude:
