# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn

  deploy-polygon:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Polygon Main Network
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      continue-on-error: true
      run: truffle migrate --network polygonMainnet --reset

  deploy-bsc:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn

    - name: Deploy to BSC Main Network
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
      continue-on-error: true
      run: truffle migrate --network bscMainnet --reset

  deploy-ethereum:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Ethereum Main Network
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
      continue-on-error: true
      run: truffle migrate --network ethereum --reset
