# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn

    - name: Check Solidity style
      run: yarn run check
    
    - name: Check JS style
      run: yarn run checkjs

    - name: Run tests
      run: yarn test

  deploy-fuji:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Avalanche Test Network
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
        ALCHEMY_API_KEY_STAGE: ${{ secrets.ALCHEMY_API_KEY_STAGE }}
      continue-on-error: true
      run: truffle migrate --network avalancheTestnet --reset

  deploy-polygon:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Polygon Test Network
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
        ALCHEMY_API_KEY_STAGE: ${{ secrets.ALCHEMY_API_KEY_STAGE }}
      continue-on-error: true
      run: truffle migrate --network polygonTestnet --reset

  deploy-bsc:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn

    - name: Deploy to BSC Test Network
      env:
        MNEMONIC: ${{ secrets.MNEMONIC }}
      continue-on-error: true
      run: truffle migrate --network bscTestnet --reset

  deploy-sepolia:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Ganache and Truffle CLI
      run: yarn global add truffle ganache
    
    - name: Start Ganache CLI
      run: ganache &

    - name: Install dependencies
      run: yarn
    
    - name: Deploy to Ethereum Sepolia Test Network
      env:
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
      continue-on-error: true
      run: truffle migrate --network sepolia --reset
