# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-solidity:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Ganache CLI
      run: yarn global add ganache-cli
    
    - name: Start Ganache CLI
      run: ganache-cli &

    - name: Install dependencies
      run: yarn

    - name: Update packages to latest version
      run: yarn upgrade
    
    - name: Check Solidity style
      run: yarn run check
    
    - name: Check JS style
      run: yarn run checkjs

    - name: Run tests
      run: yarn test
  
  test-angular:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.x 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Load cache
      uses: actions/cache@v2
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install environment
      working-directory: ./frontend
      run: |
        sudo apt update
        sudo apt install git chromium-browser
        yarn global add @angular/cli

    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install && ng update

    - name: Check style
      working-directory: ./frontend
      run: |
        yarn eslint '**/*.ts'
        yarn prettier --check '**/*.ts'

    - name: Run tests
      working-directory: ./frontend
      run: yarn test
